export const NAME_CHANGED = 'NAME_CHANGED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const SESSION_SUCCESS = 'SESSION_SUCCESS';
export const LEAVE_SUCCESS = 'LEAVE_SUCCESS';

export const MESSAGE_REQUEST = 'MESSAGE_REQUEST';
export const MESSAGE_REQUEST_SUCCESS = 'MESSAGE_REQUEST_SUCCESS';
export const MESSAGE_INPUT_CHANGED = 'MESSAGE_INPUT_CHANGED';
export const SEND_MESSAGE = 'SEND_MESSAGE';
